feat: Add MultiStore SMT manager
pokt-network/smt pull request #17
Opened 2023-07-31 12:47 UTC by h5law

## Description

This PR introduces the new `MultiStore` SMT manager. This enables the management of numerous SMTs under a single overarching tree.

The `MultiStore` acts as a wrapper around an SMT that includes the name and root hash of the trees it manages. The `Store` interface is a wrapper around a single SMT which tracks the `MultiStore` it is a part of and overwrites the SMT's `Commit` method to not only commit the `Store`'s changes to the database but also update the `MultiStore` with the name and root hash of the `Store`'s tree.

This is useful in areas where a single tree / root hash is needed but different SMT's are desired: for example in a blockchain setting this could replace the root tree and each of the trees it manages could track the transactions, accounts etc. It would also be useful for an implementation of the IBC specification where the `MultiStore` would represent the IBC store as a whole with each `Store` representing a single ICS component such as the ICS-02 store or the ICS-03 store.

reviewpad:summary

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Add the `MultiStore` and `Store` interfaces
- Add the `multi` and `store` structs to implement the interfaces
- Add unit tests
- Add documentation

## Testing

- [x] **Task specific tests or benchmarks**: `go test ...`
- [x] **New tests or benchmarks**: `go test ...`
- [x] **All tests**: `go test -v`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling

### If Applicable Checklist

- [x] Update any relevant README(s)
- [x] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams
- [x] I have added tests that prove my fix is effective or that my feature works

2023-08-30 09:36 UTC, h5law commented on multi.go
> +	multi     *multi
Should this be an interface?

2023-08-30 09:37 UTC, h5law commented on multi.go
> +type multi struct {
Should the fields be exported and have getters so you can plug and play your own and pass it as an interface into the store?

2023-09-06 04:09 UTC, Olshansk requested changes
@h5law Before I review this, can you update the description with the motivation for this?

When I saw this:
> The `MultiStore` interface grants the easy management of numerous different SMTs.

It made me feel like the multistore is outside the scope of the `smt` repo and is probably something a user of this repo would manage.

2023-09-09 09:26 UTC, h5law commented
Closing this as the MultiStore is not longer a priority.

For future reference this should be rescoped to allow the SMT to preform silimar functions to the IAVL+ tree in the context of the `CommitMultiStore` etc used in the `cosmos-sdk` [1]. Enabling the correct features for this to be plugged in place of the IAVL+ tree will be a win.

[1] https://docs.cosmos.network/v0.45/core/store.html#commitmultistore

2023-09-09 09:26 UTC, closed without merging