feat: add benchmarking suite
pokt-network/smt pull request #25
Opened 2023-09-18 10:46 UTC by h5law

## Description

reviewpad:summary

## Issue

Fixes #9 

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [x] Documentation
- [ ] Other 

## List of changes

- Add benchmarking suite for SM(S)T
- Add benchmark results to main readme

## Testing

- [x] **Task specific tests or benchmarks**: `go test ...`
- [x] **New tests or benchmarks**: `go test ...`
- [x] **All tests**: `go test -v`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling

### If Applicable Checklist

- [x] Update any relevant README(s)
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams
- [x] I have added tests that prove my fix is effective or that my feature works

2023-09-25 00:44 UTC, Olshansk requested changes

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +	treeSizes := []int{100000, 500000, 1000000, 5000000, 10000000}
```suggestion
	treeSizes := []int{100000, 500000, 1000000, 5000000, 10000000} // num leaves
```

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +	leafSizes := []int{256, 512, 1024, 2048, 4096, 8192, 16384}
```suggestion
	leafSizes := []int{256, 512, 1024, 2048, 4096, 8192, 16384} // num bytes per leaf
```

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +				name := "Fill"
s/name/operation

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +						if commit {
Do we have a test where you commit after every update and compare that?

Don't do it in this commit but leave a comment saying: `// There is an opportunity to do a fuzz test where we commit every N updates, if this ever becomes a bottlneck`

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +			for i := 0; i < 2; i++ {
NIT: `for _, operation := range []string{"Commit", "Commit & Fill"} {`

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_leaf_test.go
> +func BenchmarkSMSTLeafSizes_Fill(b *testing.B) {
Ditto everything above

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_smt_test.go
> +package smt
Dude, great job on these tests!

Finding the balance of copy-paste vs abstraction without going overboard either way isn't easy, but you fucking nailed it!

2023-09-25 00:44 UTC, Olshansk commented on benchmarks/bench_utils_test.go
> +func setupSMT(b *testing.B, persistent bool, num int) *smt.SMT {
NIT: Use a more semantic name than `num`

s/num/numLeaves

2023-09-25 12:31 UTC, h5law commented on README.md
> +go test -benchmem -run=^$ -bench Benchmark ./benchmarks -timeout 0
Yeah sure will do it in this PR I was thinking about it as well

2023-09-25 16:30 UTC, Olshansk commented on README.md
> +go test -benchmem -run=^$ -bench Benchmark ./benchmarks -timeout 0
Add TODOs for stuff like this

2023-09-26 00:15 UTC, Olshansk approved these changes
Left a couple more comments but feel free to merge after.

2023-09-26 07:29 UTC, merged